language: python

notifications:
  email:
    recipients:
      - aslak.bergersen@gmail.com
    on_success: never   # default: change
    on_failure: always  # default: always

matrix:
    include:
        - os: linux
          python: 3.6
        - os: osx
          python: 3.6


install:
  - sudo apt-get update

  # Install conda
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
       wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
    else
       wget "https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda

  # Export path
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  # Set conda parameters
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge

  # Set up environment
  - conda create -n turtleFSI fenics pytest #turtleFSI

  # Activate environment
  - source activate turtleFSI
  - python setup.py install

  # Useful for debugging any issues with conda
  - conda info -a
  
script:
  - cd tests
  - pytest .
